# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ahjs_development
test:
  <<: *default
  database: ahjs_test

production:
  <<: *default
  database: ahjs_production
  username: ahjs
  password: <%= ENV['AHJS_DATABASE_PASSWORD'] %>